// Compétences par domaine

import type { BaseModel } from "../base/base-model";

export interface ServerSkill extends BaseModel {
  value: string;
  label: string;
}

export interface SkillCategory extends BaseModel {
  category: string;
  skills: ServerSkill[];
}

export const skillsByCategory = [
  {
    category: "Développement Web",
    skills: [
      { value: "html", label: "HTML" },
      { value: "css", label: "CSS" },
      { value: "javascript", label: "JavaScript" },
      { value: "typescript", label: "TypeScript" },
      { value: "react", label: "React" },
      { value: "angular", label: "Angular" },
      { value: "vue", label: "Vue.js" },
      { value: "nextjs", label: "Next.js" },
      { value: "nodejs", label: "Node.js" },
      { value: "express", label: "Express.js" },
      { value: "php", label: "PHP" },
      { value: "laravel", label: "Laravel" },
      { value: "symfony", label: "Symfony" },
      { value: "django", label: "Django" },
      { value: "flask", label: "Flask" },
      { value: "ruby", label: "Ruby" },
      { value: "rails", label: "Ruby on Rails" },
      { value: "wordpress", label: "WordPress" },
      { value: "jquery", label: "jQuery" },
      { value: "bootstrap", label: "Bootstrap" },
      { value: "tailwind", label: "Tailwind CSS" },
      { value: "sass", label: "Sass/SCSS" },
      { value: "less", label: "Less" },
      { value: "webpack", label: "Webpack" },
      { value: "babel", label: "Babel" },
      { value: "graphql", label: "GraphQL" },
      { value: "rest", label: "REST API" },
      { value: "pwa", label: "Progressive Web Apps" },
      { value: "webrtc", label: "WebRTC" },
      { value: "websocket", label: "WebSockets" },
    ],
  },
  {
    category: "Développement Mobile",
    skills: [
      { value: "android", label: "Android" },
      { value: "ios", label: "iOS" },
      { value: "swift", label: "Swift" },
      { value: "kotlin", label: "Kotlin" },
      { value: "java-mobile", label: "Java (Mobile)" },
      { value: "react-native", label: "React Native" },
      { value: "flutter", label: "Flutter" },
      { value: "xamarin", label: "Xamarin" },
      { value: "ionic", label: "Ionic" },
      { value: "cordova", label: "Cordova" },
      { value: "capacitor", label: "Capacitor" },
      { value: "pwa-mobile", label: "PWA (Mobile)" },
    ],
  },
  {
    category: "Bases de données",
    skills: [
      { value: "mysql", label: "MySQL" },
      { value: "postgresql", label: "PostgreSQL" },
      { value: "mongodb", label: "MongoDB" },
      { value: "sqlite", label: "SQLite" },
      { value: "oracle", label: "Oracle" },
      { value: "sql-server", label: "SQL Server" },
      { value: "redis", label: "Redis" },
      { value: "firebase", label: "Firebase" },
      { value: "dynamodb", label: "DynamoDB" },
      { value: "cassandra", label: "Cassandra" },
      { value: "couchdb", label: "CouchDB" },
      { value: "neo4j", label: "Neo4j" },
      { value: "elasticsearch", label: "Elasticsearch" },
    ],
  },
  {
    category: "DevOps & Cloud",
    skills: [
      { value: "aws", label: "AWS" },
      { value: "azure", label: "Azure" },
      { value: "gcp", label: "Google Cloud" },
      { value: "docker", label: "Docker" },
      { value: "kubernetes", label: "Kubernetes" },
      { value: "jenkins", label: "Jenkins" },
      { value: "gitlab-ci", label: "GitLab CI" },
      { value: "github-actions", label: "GitHub Actions" },
      { value: "terraform", label: "Terraform" },
      { value: "ansible", label: "Ansible" },
      { value: "puppet", label: "Puppet" },
      { value: "chef", label: "Chef" },
      { value: "nginx", label: "Nginx" },
      { value: "apache", label: "Apache" },
      { value: "linux", label: "Linux" },
      { value: "bash", label: "Bash/Shell" },
      { value: "ci-cd", label: "CI/CD" },
      { value: "serverless", label: "Serverless" },
      { value: "microservices", label: "Microservices" },
    ],
  },
  {
    category: "Data Science & IA",
    skills: [
      { value: "python", label: "Python" },
      { value: "r", label: "R" },
      { value: "machine-learning", label: "Machine Learning" },
      { value: "deep-learning", label: "Deep Learning" },
      { value: "tensorflow", label: "TensorFlow" },
      { value: "pytorch", label: "PyTorch" },
      { value: "keras", label: "Keras" },
      { value: "scikit-learn", label: "Scikit-learn" },
      { value: "pandas", label: "Pandas" },
      { value: "numpy", label: "NumPy" },
      { value: "data-visualization", label: "Data Visualization" },
      { value: "tableau", label: "Tableau" },
      { value: "power-bi", label: "Power BI" },
      { value: "nlp", label: "NLP" },
      { value: "computer-vision", label: "Computer Vision" },
      { value: "big-data", label: "Big Data" },
      { value: "hadoop", label: "Hadoop" },
      { value: "spark", label: "Spark" },
    ],
  },
  {
    category: "Design & UI/UX",
    skills: [
      { value: "ui-design", label: "UI Design" },
      { value: "ux-design", label: "UX Design" },
      { value: "responsive-design", label: "Responsive Design" },
      { value: "figma", label: "Figma" },
      { value: "sketch", label: "Sketch" },
      { value: "adobe-xd", label: "Adobe XD" },
      { value: "photoshop", label: "Photoshop" },
      { value: "illustrator", label: "Illustrator" },
      { value: "indesign", label: "InDesign" },
      { value: "after-effects", label: "After Effects" },
      { value: "premiere-pro", label: "Premiere Pro" },
      { value: "motion-design", label: "Motion Design" },
      { value: "3d-modeling", label: "3D Modeling" },
      { value: "blender", label: "Blender" },
      { value: "maya", label: "Maya" },
      { value: "cinema-4d", label: "Cinema 4D" },
    ],
  },
  {
    category: "Gestion de projet",
    skills: [
      { value: "agile", label: "Agile" },
      { value: "scrum", label: "Scrum" },
      { value: "kanban", label: "Kanban" },
      { value: "jira", label: "Jira" },
      { value: "trello", label: "Trello" },
      { value: "asana", label: "Asana" },
      { value: "notion", label: "Notion" },
      { value: "confluence", label: "Confluence" },
      { value: "project-management", label: "Gestion de projet" },
      { value: "product-management", label: "Gestion de produit" },
      { value: "team-leadership", label: "Leadership d'équipe" },
    ],
  },
  {
    category: "Langages de programmation",
    skills: [
      { value: "c", label: "C" },
      { value: "cpp", label: "C++" },
      { value: "csharp", label: "C#" },
      { value: "java", label: "Java" },
      { value: "go", label: "Go" },
      { value: "rust", label: "Rust" },
      { value: "scala", label: "Scala" },
      { value: "haskell", label: "Haskell" },
      { value: "perl", label: "Perl" },
      { value: "lua", label: "Lua" },
      { value: "dart", label: "Dart" },
      { value: "elixir", label: "Elixir" },
      { value: "clojure", label: "Clojure" },
    ],
  },
  {
    category: "Qualité",
    skills: [
      { value: "qa-testing", label: "Assurance Qualité (QA)" },
      { value: "test-automation", label: "Automatisation des Tests" },
      { value: "manual-testing", label: "Tests Manuels" },
      { value: "unit-testing", label: "Tests Unitaires" },
      { value: "integration-testing", label: "Tests d'Intégration" },
      { value: "functional-testing", label: "Tests Fonctionnels" },
      { value: "regression-testing", label: "Tests de Régression" },
      { value: "performance-testing", label: "Tests de Performance" },
      { value: "load-testing", label: "Tests de Charge" },
      { value: "stress-testing", label: "Tests de Stress" },
      { value: "security-testing", label: "Tests de Sécurité" },
      { value: "penetration-testing", label: "Tests de Pénétration" },
      { value: "usability-testing", label: "Tests d'Utilisabilité" },
      { value: "accessibility-testing", label: "Tests d'Accessibilité" },
      { value: "compatibility-testing", label: "Tests de Compatibilité" },
      { value: "exploratory-testing", label: "Tests Exploratoires" },
      { value: "ad-hoc-testing", label: "Tests Ad Hoc" },
      { value: "smoke-testing", label: "Tests de Fumée" },
      { value: "sanity-testing", label: "Tests de Sanité" },
      { value: "alpha-testing", label: "Tests Alpha" },
      { value: "beta-testing", label: "Tests Beta" },
      { value: "acceptance-testing", label: "Tests d'Acceptation" },
      {
        value: "user-acceptance-testing",
        label: "Tests d'Acceptation Utilisateur (UAT)",
      },
      { value: "bdd", label: "Développement Piloté par le Comportement (BDD)" },
      { value: "tdd", label: "Développement Piloté par les Tests (TDD)" },
      {
        value: "atdd",
        label: "Développement Piloté par les Tests d'Acceptation (ATDD)",
      },
      { value: "continuous-testing", label: "Tests Continus" },
      { value: "shift-left-testing", label: "Tests Shift-Left" },
      { value: "quality-assurance", label: "Assurance Qualité" },
      { value: "quality-control", label: "Contrôle Qualité" },
      { value: "quality-engineering", label: "Ingénierie Qualité" },
      { value: "quality-management", label: "Gestion de la Qualité" },
      { value: "quality-planning", label: "Planification de la Qualité" },
      { value: "quality-improvement", label: "Amélioration de la Qualité" },
      { value: "quality-metrics", label: "Métriques de Qualité" },
      { value: "quality-standards", label: "Standards de Qualité" },
      { value: "quality-tools", label: "Outils de Qualité" },
      { value: "quality-processes", label: "Processus de Qualité" },
      { value: "quality-frameworks", label: "Frameworks de Qualité" },
      { value: "quality-methodologies", label: "Méthodologies de Qualité" },
      { value: "quality-models", label: "Modèles de Qualité" },
      { value: "quality-attributes", label: "Attributs de Qualité" },
      {
        value: "quality-characteristics",
        label: "Caractéristiques de Qualité",
      },
      { value: "quality-factors", label: "Facteurs de Qualité" },
      { value: "quality-criteria", label: "Critères de Qualité" },
      { value: "quality-requirements", label: "Exigences de Qualité" },
      { value: "quality-objectives", label: "Objectifs de Qualité" },
      { value: "quality-goals", label: "Buts de Qualité" },
      { value: "quality-targets", label: "Cibles de Qualité" },
      { value: "quality-indicators", label: "Indicateurs de Qualité" },
      { value: "quality-measures", label: "Mesures de Qualité" },
      { value: "quality-parameters", label: "Paramètres de Qualité" },
      { value: "quality-dimensions", label: "Dimensions de Qualité" },
      { value: "quality-aspects", label: "Aspects de Qualité" },
      { value: "quality-components", label: "Composants de Qualité" },
      { value: "quality-elements", label: "Éléments de Qualité" },
      { value: "quality-attributes", label: "Attributs de Qualité" },
      { value: "quality-properties", label: "Propriétés de Qualité" },
      { value: "quality-features", label: "Fonctionnalités de Qualité" },
      {
        value: "quality-characteristics",
        label: "Caractéristiques de Qualité",
      },
      { value: "quality-traits", label: "Traits de Qualité" },
      { value: "quality-factors", label: "Facteurs de Qualité" },
      { value: "quality-drivers", label: "Moteurs de Qualité" },
      { value: "quality-enablers", label: "Facilitateurs de Qualité" },
      { value: "quality-accelerators", label: "Accélérateurs de Qualité" },
      { value: "quality-catalysts", label: "Catalyseurs de Qualité" },
      { value: "quality-boosters", label: "Boosters de Qualité" },
      { value: "quality-enhancers", label: "Améliorateurs de Qualité" },
      { value: "quality-amplifiers", label: "Amplificateurs de Qualité" },
      { value: "quality-multipliers", label: "Multiplicateurs de Qualité" },
      { value: "quality-optimizers", label: "Optimiseurs de Qualité" },
      { value: "quality-maximizers", label: "Maximiseurs de Qualité" },
      { value: "quality-intensifiers", label: "Intensificateurs de Qualité" },
      { value: "quality-strengtheners", label: "Renforçateurs de Qualité" },
      { value: "quality-fortifiers", label: "Fortifiants de Qualité" },
      { value: "quality-reinforcers", label: "Renforceurs de Qualité" },
      { value: "quality-solidifiers", label: "Solidificateurs de Qualité" },
      { value: "quality-stabilizers", label: "Stabilisateurs de Qualité" },
      { value: "quality-consolidators", label: "Consolidateurs de Qualité" },
      { value: "quality-unifiers", label: "Unificateurs de Qualité" },
      { value: "quality-integrators", label: "Intégrateurs de Qualité" },
      { value: "quality-harmonizers", label: "Harmonisateurs de Qualité" },
      { value: "quality-synchronizers", label: "Synchronisateurs de Qualité" },
      { value: "quality-coordinators", label: "Coordinateurs de Qualité" },
      { value: "quality-orchestrators", label: "Orchestrateurs de Qualité" },
      { value: "quality-conductors", label: "Conducteurs de Qualité" },
      { value: "quality-directors", label: "Directeurs de Qualité" },
      { value: "quality-leaders", label: "Leaders de Qualité" },
      { value: "quality-champions", label: "Champions de Qualité" },
      { value: "quality-advocates", label: "Défenseurs de Qualité" },
      { value: "quality-ambassadors", label: "Ambassadeurs de Qualité" },
      { value: "quality-evangelists", label: "Évangélistes de Qualité" },
      { value: "quality-mentors", label: "Mentors de Qualité" },
      { value: "quality-coaches", label: "Coachs de Qualité" },
      { value: "quality-trainers", label: "Formateurs de Qualité" },
      { value: "quality-educators", label: "Éducateurs de Qualité" },
      { value: "quality-instructors", label: "Instructeurs de Qualité" },
      { value: "quality-teachers", label: "Enseignants de Qualité" },
      { value: "quality-professors", label: "Professeurs de Qualité" },
      { value: "quality-gurus", label: "Gourous de Qualité" },
      { value: "quality-experts", label: "Experts de Qualité" },
      { value: "quality-specialists", label: "Spécialistes de Qualité" },
      { value: "quality-professionals", label: "Professionnels de Qualité" },
      { value: "quality-practitioners", label: "Praticiens de Qualité" },
      { value: "quality-consultants", label: "Consultants de Qualité" },
      { value: "quality-advisors", label: "Conseillers de Qualité" },
      { value: "quality-analysts", label: "Analystes de Qualité" },
      { value: "quality-engineers", label: "Ingénieurs Qualité" },
      { value: "quality-technicians", label: "Techniciens Qualité" },
      { value: "quality-inspectors", label: "Inspecteurs Qualité" },
      { value: "quality-auditors", label: "Auditeurs Qualité" },
      { value: "quality-assessors", label: "Évaluateurs Qualité" },
      { value: "quality-reviewers", label: "Examinateurs Qualité" },
      { value: "quality-testers", label: "Testeurs Qualité" },
      { value: "quality-verifiers", label: "Vérificateurs Qualité" },
      { value: "quality-validators", label: "Validateurs Qualité" },
      { value: "quality-certifiers", label: "Certificateurs Qualité" },
      { value: "quality-approvers", label: "Approbateurs Qualité" },
      { value: "quality-authorizers", label: "Autorisateurs Qualité" },
      { value: "quality-endorsers", label: "Endosseurs Qualité" },
      { value: "quality-signatories", label: "Signataires Qualité" },
      { value: "quality-guarantors", label: "Garants Qualité" },
      { value: "quality-assurers", label: "Assureurs Qualité" },
      { value: "quality-warrantors", label: "Garants Qualité" },
      { value: "quality-backers", label: "Soutiens Qualité" },
      { value: "quality-supporters", label: "Partisans Qualité" },
      { value: "quality-promoters", label: "Promoteurs Qualité" },
      { value: "quality-sponsors", label: "Sponsors Qualité" },
      { value: "quality-patrons", label: "Mécènes Qualité" },
      { value: "quality-benefactors", label: "Bienfaiteurs Qualité" },
      { value: "quality-philanthropists", label: "Philanthropes Qualité" },
      { value: "quality-humanitarians", label: "Humanitaires Qualité" },
      { value: "quality-altruists", label: "Altruistes Qualité" },
      { value: "quality-samaritans", label: "Samaritains Qualité" },
      { value: "quality-angels", label: "Anges Qualité" },
      { value: "quality-guardians", label: "Gardiens Qualité" },
      { value: "quality-protectors", label: "Protecteurs Qualité" },
      { value: "quality-defenders", label: "Défenseurs Qualité" },
      { value: "quality-preservers", label: "Préservateurs Qualité" },
      { value: "quality-conservators", label: "Conservateurs Qualité" },
      { value: "quality-custodians", label: "Gardiens Qualité" },
      { value: "quality-keepers", label: "Gardiens Qualité" },
      { value: "quality-stewards", label: "Intendants Qualité" },
      { value: "quality-caretakers", label: "Gardiens Qualité" },
      { value: "quality-maintainers", label: "Mainteneurs Qualité" },
      { value: "quality-sustainers", label: "Souteneurs Qualité" },
      { value: "quality-perpetuators", label: "Perpétuateurs Qualité" },
      { value: "quality-continuators", label: "Continuateurs Qualité" },
      { value: "quality-extenders", label: "Extenseurs Qualité" },
      { value: "quality-expanders", label: "Expanseurs Qualité" },
      { value: "quality-enlargers", label: "Agrandisseurs Qualité" },
      { value: "quality-augmenters", label: "Augmenteurs Qualité" },
      { value: "quality-amplifiers", label: "Amplificateurs Qualité" },
      { value: "quality-magnifiers", label: "Amplificateurs Qualité" },
      { value: "quality-intensifiers", label: "Intensificateurs Qualité" },
      { value: "quality-enhancers", label: "Améliorateurs Qualité" },
      { value: "quality-enrichers", label: "Enrichisseurs Qualité" },
      { value: "quality-fortifiers", label: "Fortifiants Qualité" },
      { value: "quality-strengtheners", label: "Renforçateurs Qualité" },
      { value: "quality-reinforcers", label: "Renforceurs Qualité" },
      { value: "quality-boosters", label: "Boosters Qualité" },
      { value: "quality-catalysts", label: "Catalyseurs Qualité" },
      { value: "quality-accelerators", label: "Accélérateurs Qualité" },
      { value: "quality-expeditors", label: "Expéditeurs Qualité" },
      { value: "quality-facilitators", label: "Facilitateurs Qualité" },
      { value: "quality-enablers", label: "Facilitateurs Qualité" },
      { value: "quality-empowerers", label: "Habilitateurs Qualité" },
      { value: "quality-liberators", label: "Libérateurs Qualité" },
      { value: "quality-emancipators", label: "Émancipateurs Qualité" },
      { value: "quality-revolutionaries", label: "Révolutionnaires Qualité" },
      { value: "quality-innovators", label: "Innovateurs Qualité" },
      { value: "quality-pioneers", label: "Pionniers Qualité" },
      { value: "quality-trailblazers", label: "Pionniers Qualité" },
      { value: "quality-pathfinders", label: "Éclaireurs Qualité" },
      { value: "quality-explorers", label: "Explorateurs Qualité" },
      { value: "quality-discoverers", label: "Découvreurs Qualité" },
      { value: "quality-inventors", label: "Inventeurs Qualité" },
      { value: "quality-creators", label: "Créateurs Qualité" },
      { value: "quality-founders", label: "Fondateurs Qualité" },
      { value: "quality-originators", label: "Initiateurs Qualité" },
      { value: "quality-initiators", label: "Initiateurs Qualité" },
      { value: "quality-instigators", label: "Instigateurs Qualité" },
      { value: "quality-catalysts", label: "Catalyseurs Qualité" },
      { value: "quality-triggers", label: "Déclencheurs Qualité" },
      { value: "quality-stimulators", label: "Stimulateurs Qualité" },
      { value: "quality-activators", label: "Activateurs Qualité" },
      { value: "quality-energizers", label: "Énergiseurs Qualité" },
      { value: "quality-vitalizers", label: "Vitaliseurs Qualité" },
      { value: "quality-revitalizers", label: "Revitaliseurs Qualité" },
      { value: "quality-rejuvenators", label: "Rajeunisseurs Qualité" },
      { value: "quality-renewers", label: "Renouveleurs Qualité" },
      { value: "quality-refreshers", label: "Rafraîchisseurs Qualité" },
      { value: "quality-restorers", label: "Restaurateurs Qualité" },
      { value: "quality-rehabilitators", label: "Réhabilitateurs Qualité" },
      { value: "quality-regenerators", label: "Régénérateurs Qualité" },
      { value: "quality-resuscitators", label: "Ressusciteurs Qualité" },
      { value: "quality-revivers", label: "Raviveurs Qualité" },
      { value: "quality-reanimators", label: "Réanimateurs Qualité" },
      { value: "quality-resurrectors", label: "Résurrecteurs Qualité" },
      { value: "quality-revivifiers", label: "Revivificateurs Qualité" },
      { value: "quality-revitalizers", label: "Revitaliseurs Qualité" },
      { value: "quality-reinvigorators", label: "Revigorants Qualité" },
      { value: "quality-reenergizers", label: "Réénergiseurs Qualité" },
      { value: "quality-rechargers", label: "Rechargeurs Qualité" },
      { value: "quality-refuelers", label: "Ravitailleurs Qualité" },
      { value: "quality-replenishers", label: "Réapprovisioneurs Qualité" },
      { value: "quality-restockers", label: "Réapprovisionneurs Qualité" },
      { value: "quality-resuppliers", label: "Réapprovisionneurs Qualité" },
      { value: "quality-reinforcers", label: "Renforceurs Qualité" },
      { value: "quality-strengtheners", label: "Renforçateurs Qualité" },
      { value: "quality-fortifiers", label: "Fortifiants Qualité" },
      { value: "quality-enhancers", label: "Améliorateurs Qualité" },
      { value: "quality-enrichers", label: "Enrichisseurs Qualité" },
      { value: "quality-augmenters", label: "Augmenteurs Qualité" },
      { value: "quality-amplifiers", label: "Amplificateurs Qualité" },
      { value: "quality-magnifiers", label: "Amplificateurs Qualité" },
      { value: "quality-intensifiers", label: "Intensificateurs Qualité" },
      { value: "quality-boosters", label: "Boosters Qualité" },
      { value: "quality-catalysts", label: "Catalyseurs Qualité" },
      { value: "quality-accelerators", label: "Accélérateurs Qualité" },
      { value: "quality-expeditors", label: "Expéditeurs Qualité" },
      { value: "quality-facilitators", label: "Facilitateurs Qualité" },
      { value: "quality-enablers", label: "Facilitateurs Qualité" },
      { value: "quality-empowerers", label: "Habilitateurs Qualité" },
      { value: "quality-liberators", label: "Libérateurs Qualité" },
      { value: "quality-emancipators", label: "Émancipateurs Qualité" },
      { value: "quality-revolutionaries", label: "Révolutionnaires Qualité" },
      { value: "quality-innovators", label: "Innovateurs Qualité" },
      { value: "quality-pioneers", label: "Pionniers Qualité" },
      { value: "quality-trailblazers", label: "Pionniers Qualité" },
      { value: "quality-pathfinders", label: "Éclaireurs Qualité" },
      { value: "quality-explorers", label: "Explorateurs Qualité" },
      { value: "quality-discoverers", label: "Découvreurs Qualité" },
      { value: "quality-inventors", label: "Inventeurs Qualité" },
      { value: "quality-creators", label: "Créateurs Qualité" },
      { value: "quality-founders", label: "Fondateurs Qualité" },
      { value: "quality-originators", label: "Initiateurs Qualité" },
      { value: "quality-initiators", label: "Initiateurs Qualité" },
      { value: "quality-instigators", label: "Instigateurs Qualité" },
      { value: "quality-catalysts", label: "Catalyseurs Qualité" },
      { value: "quality-triggers", label: "Déclencheurs Qualité" },
      { value: "quality-stimulators", label: "Stimulateurs Qualité" },
      { value: "quality-activators", label: "Activateurs Qualité" },
    ],
  },
  {
    category: "Normes et Certifications",
    skills: [
      {
        value: "iso-9001",
        label: "ISO 9001 - Système de management de la qualité",
      },
      {
        value: "iso-14001",
        label: "ISO 14001 - Système de management environnemental",
      },
      { value: "iso-27001", label: "ISO 27001 - Sécurité de l'information" },
      { value: "iso-45001", label: "ISO 45001 - Santé et sécurité au travail" },
      { value: "iso-13485", label: "ISO 13485 - Dispositifs médicaux" },
      {
        value: "iso-22000",
        label: "ISO 22000 - Sécurité des denrées alimentaires",
      },
      { value: "iso-50001", label: "ISO 50001 - Management de l'énergie" },
      {
        value: "iso-20000",
        label: "ISO 20000 - Gestion des services informatiques",
      },
      { value: "iso-31000", label: "ISO 31000 - Management du risque" },
      { value: "iso-26000", label: "ISO 26000 - Responsabilité sociétale" },
      {
        value: "iso-17025",
        label: "ISO 17025 - Laboratoires d'essais et d'étalonnage",
      },
      { value: "iso-22301", label: "ISO 22301 - Continuité d'activité" },
      {
        value: "iso-37001",
        label: "ISO 37001 - Systèmes de management anti-corruption",
      },
      { value: "iso-21001", label: "ISO 21001 - Organismes d'éducation" },
      { value: "iso-41001", label: "ISO 41001 - Facility management" },
      { value: "iso-55001", label: "ISO 55001 - Gestion d'actifs" },
      {
        value: "iso-28000",
        label: "ISO 28000 - Sécurité de la chaîne d'approvisionnement",
      },
      {
        value: "iso-29001",
        label: "ISO 29001 - Pétrole, pétrochimie et gaz naturel",
      },
      { value: "iso-16949", label: "IATF 16949 - Industrie automobile" },
      { value: "as9100", label: "AS9100 - Aéronautique et spatial" },
      { value: "iso-22716", label: "ISO 22716 - Cosmétiques" },
      {
        value: "haccp",
        label: "HACCP - Analyse des dangers et points critiques",
      },
      { value: "fssc-22000", label: "FSSC 22000 - Sécurité alimentaire" },
      { value: "brc", label: "BRC - British Retail Consortium" },
      { value: "ifs", label: "IFS - International Featured Standards" },
      { value: "gmp", label: "GMP - Bonnes pratiques de fabrication" },
      { value: "gdp", label: "GDP - Bonnes pratiques de distribution" },
      { value: "gcp", label: "GCP - Bonnes pratiques cliniques" },
      { value: "glp", label: "GLP - Bonnes pratiques de laboratoire" },
      { value: "gxp", label: "GxP - Ensemble des bonnes pratiques" },
      { value: "cmmi", label: "CMMI - Capability Maturity Model Integration" },
      {
        value: "itil",
        label: "ITIL - Information Technology Infrastructure Library",
      },
      {
        value: "cobit",
        label: "COBIT - Control Objectives for Information Technologies",
      },
      {
        value: "pci-dss",
        label: "PCI DSS - Payment Card Industry Data Security Standard",
      },
      { value: "soc", label: "SOC - Service Organization Control" },
      {
        value: "hipaa",
        label: "HIPAA - Health Insurance Portability and Accountability Act",
      },
      {
        value: "gdpr",
        label: "RGPD - Règlement général sur la protection des données",
      },
      { value: "sox", label: "SOX - Sarbanes-Oxley" },
      { value: "basel", label: "Bâle - Normes bancaires" },
      { value: "solvency", label: "Solvabilité II - Assurance" },
      { value: "mifid", label: "MiFID - Marchés d'instruments financiers" },
      { value: "aml", label: "AML - Anti-blanchiment d'argent" },
      { value: "fatca", label: "FATCA - Foreign Account Tax Compliance Act" },
      { value: "crs", label: "CRS - Common Reporting Standard" },
      {
        value: "leed",
        label: "LEED - Leadership in Energy and Environmental Design",
      },
      {
        value: "breeam",
        label:
          "BREEAM - Building Research Establishment Environmental Assessment Method",
      },
      { value: "hqe", label: "HQE - Haute Qualité Environnementale" },
      { value: "energy-star", label: "Energy Star" },
      { value: "ce-marking", label: "Marquage CE" },
      { value: "ul", label: "UL - Underwriters Laboratories" },
      { value: "csa", label: "CSA - Canadian Standards Association" },
      { value: "rohs", label: "RoHS - Restriction of Hazardous Substances" },
      {
        value: "reach",
        label:
          "REACH - Enregistrement, évaluation et autorisation des substances chimiques",
      },
      {
        value: "weee",
        label: "DEEE - Déchets d'équipements électriques et électroniques",
      },
      { value: "ecolabel", label: "Écolabel" },
      { value: "fairtrade", label: "Commerce équitable" },
      { value: "organic", label: "Agriculture biologique" },
      { value: "msc", label: "MSC - Marine Stewardship Council" },
      { value: "fsc", label: "FSC - Forest Stewardship Council" },
      {
        value: "pefc",
        label: "PEFC - Programme for the Endorsement of Forest Certification",
      },
      { value: "sa8000", label: "SA8000 - Responsabilité sociale" },
      {
        value: "ohsas-18001",
        label: "OHSAS 18001 - Santé et sécurité au travail",
      },
      {
        value: "efqm",
        label: "EFQM - European Foundation for Quality Management",
      },
      { value: "six-sigma", label: "Six Sigma" },
      { value: "lean", label: "Lean Management" },
      { value: "kaizen", label: "Kaizen" },
      { value: "tqm", label: "TQM - Total Quality Management" },
      { value: "5s", label: "5S - Méthode d'organisation" },
      { value: "8d", label: "8D - Eight Disciplines Problem Solving" },
      { value: "pdca", label: "PDCA - Plan-Do-Check-Act" },
      {
        value: "dmaic",
        label: "DMAIC - Define, Measure, Analyze, Improve, Control",
      },
      {
        value: "fmea",
        label:
          "AMDEC - Analyse des modes de défaillance, de leurs effets et de leur criticité",
      },
      { value: "apqp", label: "APQP - Advanced Product Quality Planning" },
      { value: "ppap", label: "PPAP - Production Part Approval Process" },
      { value: "msa", label: "MSA - Measurement System Analysis" },
      { value: "spc", label: "SPC - Statistical Process Control" },
      { value: "capa", label: "CAPA - Corrective and Preventive Actions" },
      { value: "qfd", label: "QFD - Quality Function Deployment" },
      { value: "doe", label: "DOE - Design of Experiments" },
      { value: "poka-yoke", label: "Poka-Yoke - Détrompeur" },
      { value: "kanban", label: "Kanban" },
      { value: "jit", label: "JIT - Just In Time" },
      { value: "tpm", label: "TPM - Total Productive Maintenance" },
      { value: "smed", label: "SMED - Single Minute Exchange of Die" },
      { value: "oee", label: "OEE - Overall Equipment Effectiveness" },
      { value: "vsm", label: "VSM - Value Stream Mapping" },
      { value: "gemba", label: "Gemba Walk" },
      { value: "ishikawa", label: "Diagramme d'Ishikawa" },
      { value: "pareto", label: "Analyse de Pareto" },
      { value: "mtbf", label: "MTBF - Mean Time Between Failures" },
      { value: "mttr", label: "MTTR - Mean Time To Repair" },
      { value: "mttf", label: "MTTF - Mean Time To Failure" },
      { value: "mdt", label: "MDT - Mean Down Time" },
      { value: "reliability", label: "Fiabilité" },
      { value: "maintainability", label: "Maintenabilité" },
      { value: "availability", label: "Disponibilité" },
      { value: "safety", label: "Sécurité" },
      { value: "security", label: "Sûreté" },
      { value: "durability", label: "Durabilité" },
      { value: "resilience", label: "Résilience" },
      { value: "robustness", label: "Robustesse" },
      { value: "sustainability", label: "Développement durable" },
      { value: "circular-economy", label: "Économie circulaire" },
      { value: "csr", label: "RSE - Responsabilité sociétale des entreprises" },
      { value: "esg", label: "ESG - Environnement, Social et Gouvernance" },
      { value: "sdg", label: "ODD - Objectifs de développement durable" },
      { value: "carbon-footprint", label: "Empreinte carbone" },
      { value: "life-cycle-assessment", label: "Analyse du cycle de vie" },
      { value: "eco-design", label: "Éco-conception" },
      { value: "green-it", label: "Green IT" },
      { value: "energy-efficiency", label: "Efficacité énergétique" },
      { value: "water-management", label: "Gestion de l'eau" },
      { value: "waste-management", label: "Gestion des déchets" },
      { value: "pollution-prevention", label: "Prévention de la pollution" },
      { value: "biodiversity", label: "Biodiversité" },
      { value: "climate-change", label: "Changement climatique" },
      { value: "renewable-energy", label: "Énergies renouvelables" },
      { value: "clean-tech", label: "Technologies propres" },
    ],
  },
  {
    category: "Autres",
    skills: [
      { value: "git", label: "Git" },
      { value: "seo", label: "SEO" },
      { value: "analytics", label: "Analytics" },
      { value: "testing", label: "Testing" },
      { value: "jest", label: "Jest" },
      { value: "mocha", label: "Mocha" },
      { value: "cypress", label: "Cypress" },
      { value: "selenium", label: "Selenium" },
      { value: "accessibility", label: "Accessibilité" },
      { value: "i18n", label: "Internationalisation" },
      { value: "blockchain", label: "Blockchain" },
      { value: "ar-vr", label: "AR/VR" },
      { value: "iot", label: "IoT" },
      { value: "game-development", label: "Développement de jeux" },
      { value: "unity", label: "Unity" },
      { value: "unreal-engine", label: "Unreal Engine" },
    ],
  },
];

// Liste plate de toutes les compétences
export const allSkills = skillsByCategory.flatMap(
  (category) => category.skills,
);

// // Liste des langues
// export const languages = [
//   { value: "fr", label: "Français" },
//   { value: "en", label: "Anglais" },
//   { value: "es", label: "Espagnol" },
//   { value: "de", label: "Allemand" },
//   { value: "it", label: "Italien" },
//   { value: "pt", label: "Portugais" },
//   { value: "nl", label: "Néerlandais" },
//   { value: "ru", label: "Russe" },
//   { value: "zh", label: "Chinois (Mandarin)" },
//   { value: "ja", label: "Japonais" },
//   { value: "ko", label: "Coréen" },
//   { value: "ar", label: "Arabe" },
//   { value: "hi", label: "Hindi" },
//   { value: "bn", label: "Bengali" },
//   { value: "pa", label: "Pendjabi" },
//   { value: "tr", label: "Turc" },
//   { value: "pl", label: "Polonais" },
//   { value: "uk", label: "Ukrainien" },
//   { value: "sv", label: "Suédois" },
//   { value: "no", label: "Norvégien" },
//   { value: "da", label: "Danois" },
//   { value: "fi", label: "Finnois" },
//   { value: "el", label: "Grec" },
//   { value: "cs", label: "Tchèque" },
//   { value: "hu", label: "Hongrois" },
//   { value: "ro", label: "Roumain" },
//   { value: "bg", label: "Bulgare" },
//   { value: "hr", label: "Croate" },
//   { value: "sr", label: "Serbe" },
//   { value: "sk", label: "Slovaque" },
//   { value: "sl", label: "Slovène" },
//   { value: "et", label: "Estonien" },
//   { value: "lv", label: "Letton" },
//   { value: "lt", label: "Lituanien" },
//   { value: "he", label: "Hébreu" },
//   { value: "th", label: "Thaï" },
//   { value: "vi", label: "Vietnamien" },
//   { value: "id", label: "Indonésien" },
//   { value: "ms", label: "Malais" },
//   { value: "fa", label: "Persan" },
//   { value: "ur", label: "Ourdou" },
//   { value: "sw", label: "Swahili" },
//   { value: "am", label: "Amharique" },
//   { value: "zu", label: "Zoulou" },
//   { value: "xh", label: "Xhosa" },
//   { value: "yo", label: "Yoruba" },
//   { value: "ig", label: "Igbo" },
//   { value: "ha", label: "Haoussa" },
// ]

// // Liste des pays pour la localisation
// export const countries = [
//   { value: "fr", label: "France" },
//   { value: "us", label: "États-Unis" },
//   { value: "ca", label: "Canada" },
//   { value: "gb", label: "Royaume-Uni" },
//   { value: "de", label: "Allemagne" },
//   { value: "es", label: "Espagne" },
//   { value: "it", label: "Italie" },
//   { value: "pt", label: "Portugal" },
//   { value: "nl", label: "Pays-Bas" },
//   { value: "be", label: "Belgique" },
//   { value: "ch", label: "Suisse" },
//   { value: "at", label: "Autriche" },
//   { value: "se", label: "Suède" },
//   { value: "dk", label: "Danemark" },
//   { value: "no", label: "Norvège" },
//   { value: "fi", label: "Finlande" },
//   { value: "ie", label: "Irlande" },
//   { value: "lu", label: "Luxembourg" },
//   { value: "gr", label: "Grèce" },
//   { value: "pl", label: "Pologne" },
//   { value: "cz", label: "République tchèque" },
//   { value: "hu", label: "Hongrie" },
//   { value: "ro", label: "Roumanie" },
//   { value: "bg", label: "Bulgarie" },
//   { value: "hr", label: "Croatie" },
//   { value: "si", label: "Slovénie" },
//   { value: "sk", label: "Slovaquie" },
//   { value: "ee", label: "Estonie" },
//   { value: "lv", label: "Lettonie" },
//   { value: "lt", label: "Lituanie" },
//   { value: "cy", label: "Chypre" },
//   { value: "mt", label: "Malte" },
//   { value: "jp", label: "Japon" },
//   { value: "cn", label: "Chine" },
//   { value: "kr", label: "Corée du Sud" },
//   { value: "in", label: "Inde" },
//   { value: "au", label: "Australie" },
//   { value: "nz", label: "Nouvelle-Zélande" },
//   { value: "za", label: "Afrique du Sud" },
//   { value: "br", label: "Brésil" },
//   { value: "mx", label: "Mexique" },
//   { value: "ar", label: "Argentine" },
//   { value: "cl", label: "Chili" },
//   { value: "co", label: "Colombie" },
//   { value: "pe", label: "Pérou" },
//   { value: "ve", label: "Venezuela" },
//   { value: "ma", label: "Maroc" },
//   { value: "dz", label: "Algérie" },
//   { value: "tn", label: "Tunisie" },
//   { value: "eg", label: "Égypte" },
// ]

// // Codes téléphoniques internationaux
// export const phoneCodes = [
//   { value: "+33", label: "France (+33)" },
//   { value: "+1", label: "États-Unis & Canada (+1)" },
//   { value: "+44", label: "Royaume-Uni (+44)" },
//   { value: "+49", label: "Allemagne (+49)" },
//   { value: "+34", label: "Espagne (+34)" },
//   { value: "+39", label: "Italie (+39)" },
//   { value: "+351", label: "Portugal (+351)" },
//   { value: "+31", label: "Pays-Bas (+31)" },
//   { value: "+32", label: "Belgique (+32)" },
//   { value: "+41", label: "Suisse (+41)" },
//   { value: "+43", label: "Autriche (+43)" },
//   { value: "+46", label: "Suède (+46)" },
//   { value: "+45", label: "Danemark (+45)" },
//   { value: "+47", label: "Norvège (+47)" },
//   { value: "+358", label: "Finlande (+358)" },
//   { value: "+353", label: "Irlande (+353)" },
//   { value: "+352", label: "Luxembourg (+352)" },
//   { value: "+30", label: "Grèce (+30)" },
//   { value: "+48", label: "Pologne (+48)" },
//   { value: "+420", label: "République tchèque (+420)" },
//   { value: "+36", label: "Hongrie (+36)" },
//   { value: "+40", label: "Roumanie (+40)" },
//   { value: "+359", label: "Bulgarie (+359)" },
//   { value: "+385", label: "Croatie (+385)" },
//   { value: "+386", label: "Slovénie (+386)" },
//   { value: "+421", label: "Slovaquie (+421)" },
//   { value: "+372", label: "Estonie (+372)" },
//   { value: "+371", label: "Lettonie (+371)" },
//   { value: "+370", label: "Lituanie (+370)" },
//   { value: "+357", label: "Chypre (+357)" },
//   { value: "+356", label: "Malte (+356)" },
//   { value: "+81", label: "Japon (+81)" },
//   { value: "+86", label: "Chine (+86)" },
//   { value: "+82", label: "Corée du Sud (+82)" },
//   { value: "+91", label: "Inde (+91)" },
//   { value: "+61", label: "Australie (+61)" },
//   { value: "+64", label: "Nouvelle-Zélande (+64)" },
//   { value: "+27", label: "Afrique du Sud (+27)" },
//   { value: "+55", label: "Brésil (+55)" },
//   { value: "+52", label: "Mexique (+52)" },
//   { value: "+54", label: "Argentine (+54)" },
//   { value: "+56", label: "Chili (+56)" },
//   { value: "+57", label: "Colombie (+57)" },
//   { value: "+51", label: "Pérou (+51)" },
//   { value: "+58", label: "Venezuela (+58)" },
//   { value: "+212", label: "Maroc (+212)" },
//   { value: "+213", label: "Algérie (+213)" },
//   { value: "+216", label: "Tunisie (+216)" },
//   { value: "+20", label: "Égypte (+20)" },
//   { value: "+7", label: "Russie (+7)" },
//   { value: "+380", label: "Ukraine (+380)" },
//   { value: "+90", label: "Turquie (+90)" },
//   { value: "+972", label: "Israël (+972)" },
//   { value: "+966", label: "Arabie Saoudite (+966)" },
//   { value: "+971", label: "Émirats arabes unis (+971)" },
//   { value: "+974", label: "Qatar (+974)" },
//   { value: "+961", label: "Liban (+961)" },
//   { value: "+962", label: "Jordanie (+962)" },
//   { value: "+60", label: "Malaisie (+60)" },
//   { value: "+65", label: "Singapour (+65)" },
//   { value: "+66", label: "Thaïlande (+66)" },
//   { value: "+84", label: "Vietnam (+84)" },
//   { value: "+62", label: "Indonésie (+62)" },
//   { value: "+63", label: "Philippines (+63)" },
//   { value: "+880", label: "Bangladesh (+880)" },
//   { value: "+92", label: "Pakistan (+92)" },
//   { value: "+234", label: "Nigeria (+234)" },
//   { value: "+254", label: "Kenya (+254)" },
//   { value: "+233", label: "Ghana (+233)" },
//   { value: "+225", label: "Côte d'Ivoire (+225)" },
//   { value: "+237", label: "Cameroun (+237)" },
//   { value: "+221", label: "Sénégal (+221)" },
// ]
